### ISSUE TITLE
Is there available a backend management demo?

### ISSUE THREAD

**Issue by ttodua** [MrLemur/bottle-radio#20]
i.e. AzuraCast has web-based panel, from where people manages everything (station, account, settings..), and its demo is available.
Is anything similar available for bottleratio, so we could see how backend management panel looks like?

**Comment by MrLemur** [comment]
Hi @ttodua, there is no management interface just now. Mostly everything is managed via configuration files. The only interface likely to be used is Mopidy Iris, which you can see here: https://github.com/jaedb/Iris
