### ISSUE TITLE
Is there a missing section between the end of installation and getting started?

### ISSUE THREAD

**Issue by Atari420** [MrLemur/bottle-radio#39]
**Describe the bug**
Docs go from installation to "visit spotify.your.doman/" however this fails with a 404.
The docs dont mention set up of SSL anywhere and even when going insecure it's still a 404

**To Reproduce**
1. Install 
2. Try to visit https://spotify.your.domain
3. SSL warning page
4. Click through "unsafe" and you get a 404

**Expected behavior**
I expected the set up page to load

**Screenshots**
![ssl fail no site to load](https://user-images.githubusercontent.com/92850656/149522553-9152f419-fdc3-4839-9e68-46c20350a071.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version latest

**Comment by MrLemur** [comment]
Traefik takes care of all SSL automatically through LetsEncrypt. Can you post the output of `docker-compose logs traefik` from the root directory?

**Comment by Nova1545** [comment]
For the sake of internal testing do we need the SSL for this to work? I am otherwise getting the same 404 page not found error

**Comment by MrLemur** [comment]
> 

For local testing, use the domain `docker.localhost` (should be in the README). Once the station is deployed on a real domain, Traefik will take care of the SSL certificates.

In Chrome, you can bypass all certificate warnings by setting this flag to enabled: `chrome://flags/#allow-insecure-localhost`

**Comment by MrLemur** [comment]
Closing as no reply from OP
